services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    ports:
      - "5000:5000"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    networks:
      - elk

volumes:
  esdata:
    driver: local
  kibana-data:
    driver: local
networks:
  elk:
    driver: bridge
